INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (1, 'Vidrieria');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (2, 'Metales');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (3, 'Alimento');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (4, 'Material de oficina');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (5, 'Electrodomesticos');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (6, 'Articulos de limpieza');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (7, 'Ropa');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (8, 'Video Juegos');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (9, 'Libros');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (10, 'Peliculas');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (11, 'Juguetes');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (12, 'Medicinas');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (13, 'Articulos de cocina');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (14, 'Muebles');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (15, 'Herramientas');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (16, 'Adornos');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (17, 'Software');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (18, 'Computadoras');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (19, 'Industrial y Cientifico');
INSERT INTO "TipoPaquete" ("COD", "Clasificacion") VALUES (20, 'Suplementos para mascotas');